/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
 * Generated on: 01-Oct-2018 17:25:22
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const uint16_t BL = 51;
const uint32_t B[51] = {
      -1973748,    -5836208,    -5340691,     7862879,    29315138,    37261344,
      16461120,   -14076152,   -16528718,    13111374,    29794008,      753470,
     -36311640,   -19124722,    37454540,    44549644,   -26406520,   -73531696,
      -2221636,   102628896,    58761676,  -127516544,  -176752992,   144282784,
     665752512,   923520768,   665752512,   144282784,  -176752992,  -127516544,
      58761676,   102628896,    -2221636,   -73531696,   -26406520,    44549644,
      37454540,   -19124722,   -36311640,      753470,    29794008,    13111374,
     -16528718,   -14076152,    16461120,    37261344,    29315138,     7862879,
      -5340691,    -5836208,    -1973748
};
